/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sound

import processing.core.*
import sound.ui.*
import java.util.*
import kotlin.collections.ArrayList

// Main
class Processing: PApplet() {
    private val uiComponents: TreeSet<Component> = TreeSet()
    private val tempRemove = ArrayList<Component>()
    private val tempCreate = ArrayList<Component>()

    override fun settings() {
        size(800, 800)
    }
    
    override fun setup() {
        
    }
    
    override fun draw() {
        applyAllTemp()

        for (component in uiComponents) {
            val state = component.update()

            if (state == State.Kill) {
                tempRemove.add(component)
            }

            component.display()
        }
    }

    private fun applyAllTemp() {
        removeAllTemp()
        createAllTemp()
    }

    private fun removeAllTemp() {
        for (component in tempRemove) {
            component.onDestroy()
            uiComponents.remove(component)
        }
        tempRemove.clear()
    }

    private fun createAllTemp() {
        for (component in tempCreate) {
            component.onCreated()
            uiComponents.add(component)
        }
        tempCreate.clear()
    }

    fun createComponent(component: Component) = tempCreate.add(component)
    fun removeComponent(component: Component) = tempRemove.add(component)
}

fun main() {
    PApplet.main("sound.Processing")
}
