/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sound

import processing.core.*

// Main
class Processing: PApplet() {
    override fun settings() {
        size(800, 800)
    }
    
    override fun setup() {
        
    }
    
    override fun draw() {
        
    }
}

fun main() {
    PApplet.main("sound.Processing")
}
