/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sound

import processing.core.*
import sound.rust.Rust
import sound.ui.*
import sound.ui.filter.Filter
import java.io.File

// Main
class Processing: AdvancedPApplet() {
    val ui = UI(this)

    override fun settings() {
        Rust.start()
        size(800, 800)
    }
    
    override fun setup() {
        ui.setup()
    }
    
    override fun draw() {
        ui.draw()
    }

    override fun mousePressed() {
        ui.mousePressed()
    }

    override fun mouseReleased() {
        ui.mouseReleased()
    }

    fun fileSelected(selection: File?) {
        println(selection)
        selection?.let {
            Filter.currentAudio = it.absolutePath
        }
    }
}

fun main() {
    PApplet.main("sound.Processing")
}
